### PR TITLE
Update master branch to upstream

### PR DESCRIPTION
**Pull request by djmetzle**
We keep a master and `ifixit-production` branch, separately. To make things a little cleaner, lets `git pull` the master branch, first.

Then we can use this as the base to merge the changes to the `ifixit-production` branch.

qa_req 0

### CODE REVIEW

**Comment by BaseInfinity** [comment]
CR :bikini: i trust u

**Comment by djmetzle** [comment]
@BaseInfinity Dont trust me 👇 trust Jenkin's

**Comment by copperwall** [comment]
CR 🔥

**Comment by lexahall** [comment]
what does QA look like for this?

**Comment by djmetzle** [comment]
Updated the pull description with `qa_req 0`.

There is no QA for this, it's the upstream from the Errbit project.

**Comment by djmetzle** [comment]
@danielbeardsley how do you feel about merging this? We only use the `ifixit-production` branch, right?

**Comment by danielbeardsley** [comment]
Fine by me, though since we don't really use the master branch, this doesn't have an affect, right?

**Pull request merged**
