### PR TITLE
Updates from upstream

### PR DESCRIPTION
**Pull request by djmetzle**
To address this issue:
https://github.com/iFixit/server-templates/issues/649

I've pulled Errbit master onto a branch from `ifixit_production`. There were some _funky_ merge commits to deal with, but after figuring them out, most weren't too bad.

There was a conflict with our sparklines, and our slack message format. Everything else, it looked like upstream had right.

QA
---
We should boot up a testmode stats instance and manually switching over to this branch.

CC @danielbeardsley @g1y

### CODE REVIEW

**Comment by djmetzle** [comment]
Weird. The conflict diff is all the bits i tried to fix.

@danielbeardsley or @g1y you want to check this out and make sure i made the right decisions?

**Comment by g1y** [comment]
@djmetzle Yeah! Also, I'm going to set up travis CI since it has a travis file.

**Comment by g1y** [comment]
It looksl ike you did a rebase? Shouldn't this be a merge of the upstream into our branch?

**Comment by djmetzle** [comment]
Okay, force reset to ifixit-production

**Comment by djmetzle** [comment]
I did a merge, not a pull, now.

**Comment by g1y** [comment]
CR 👍 trust fall

**Comment by g1y** [comment]
For the test failures, I think this shouldn't prevent you from merging. I would like to see them fixed in a different pull.

**Comment by BaseInfinity** [comment]
CR :itrustu:

**Comment by entendu** [comment]
What's up with this

**Comment by djmetzle** [comment]
This is all kinds of ate up. We can do better.

**Pull request closed without merging**
