### PR TITLE
Upgrade errbit to latest

### PR DESCRIPTION
**Pull request by djmetzle**
The PR reverts @addison-grant manual bundler update:
https://github.com/iFixit/errbit/commit/6dd4e3f963dda46472d2fdd962801f671496bc28

That puts us back to upstream `master` except for my slack notification changes:
https://github.com/errbit/errbit/commit/bbca210d3232c17067529d0dc3fa28868ef48150

With those changes, upstream master merged without conflict.

Hopefully this fixes the auth problem?
Ref: https://github.com/iFixit/ifixit/issues/32393

CC @iFixit/devops @addison-grant

### CODE REVIEW

**Comment by danielbeardsley** [comment]
CR 👍

**Comment by addison-grant** [comment]
@djmetzle do you have a good way to test this? Can we set up a cominor errbit temporarily and point one of our subdomains at it?

**Comment by davidrans** [comment]
CR :coffee:

**Comment by djmetzle** [comment]
QA stats machine boot incoming. There wasn't a huge amount of dev on errbit since the last updated. Hopefully the github auth fix happened in one of the upstream dependencies? Faraday is mentioned in the email as the user-agent.

**Comment by djmetzle** [comment]
We booted up a tester `stats` machine, and it serves Errbit just fine. Talked to @addison-grant and we poked around. Seems like nothing huge has changed here. QA :shipit:

**Comment by djmetzle** [comment]
I found this comment that makes me think this is the right thing:
https://github.com/errbit/errbit/pull/1464#issuecomment-587690848

**Comment by djmetzle** [comment]
Yeah, see this comment: https://github.com/errbit/errbit/issues/1463#issuecomment-587702666

**Pull request merged**
